// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// paralelUzaklikC
NumericMatrix paralelUzaklikC(NumericMatrix X, int threads);
RcppExport SEXP _ExamplePackage07_paralelUzaklikC(SEXP XSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(paralelUzaklikC(X, threads));
    return rcpp_result_gen;
END_RCPP
}
// hareketliOrtalamaC
NumericVector hareketliOrtalamaC(NumericVector x, int n);
RcppExport SEXP _ExamplePackage07_hareketliOrtalamaC(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(hareketliOrtalamaC(x, n));
    return rcpp_result_gen;
END_RCPP
}
// grupOzetC
List grupOzetC(NumericVector x, CharacterVector grup);
RcppExport SEXP _ExamplePackage07_grupOzetC(SEXP xSEXP, SEXP grupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type grup(grupSEXP);
    rcpp_result_gen = Rcpp::wrap(grupOzetC(x, grup));
    return rcpp_result_gen;
END_RCPP
}
// vektorKareC
NumericVector vektorKareC(NumericVector x);
RcppExport SEXP _ExamplePackage07_vektorKareC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(vektorKareC(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ExamplePackage07_paralelUzaklikC", (DL_FUNC) &_ExamplePackage07_paralelUzaklikC, 2},
    {"_ExamplePackage07_hareketliOrtalamaC", (DL_FUNC) &_ExamplePackage07_hareketliOrtalamaC, 2},
    {"_ExamplePackage07_grupOzetC", (DL_FUNC) &_ExamplePackage07_grupOzetC, 2},
    {"_ExamplePackage07_vektorKareC", (DL_FUNC) &_ExamplePackage07_vektorKareC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ExamplePackage07(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
