# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ ve OpenMP ile Paralel Mesafe Matrisi Hesaplama
#'
#' Bu fonksiyon, verilen bir matrisin satırları arasındaki
#' Öklid mesafelerini paralel olarak hesaplar.
#'
#' @param X Sayısal bir matris (satırlar gözlemleri, sütunlar özellikleri temsil eder).
#' @param threads Kullanılacak iş parçacığı sayısı. 0 verilirse sistemdeki tüm çekirdekler kullanılır.
#' @return N x N boyutunda bir mesafe matrisi.
#' @export
paralelUzaklikC <- function(X, threads = 0L) {
    .Call(`_ExamplePackage07_paralelUzaklikC`, X, threads)
}

#' C++ ile Hızlı Hareketli Ortalama (Rolling Mean) Hesaplama
#'
#' Bu fonksiyon, sayısal bir vektör üzerinde belirtilen pencere boyutuna göre
#' hızlıca hareketli ortalama hesaplar.
#'
#' @param x Sayısal vektör.
#' @param n Pencere boyutu (pozitif bir tam sayı).
#' @return Giriş vektörüyle aynı uzunlukta hareketli ortalamaları içeren vektör. İlk n-1 eleman NA olacaktır.
#' @export
hareketliOrtalamaC <- function(x, n) {
    .Call(`_ExamplePackage07_hareketliOrtalamaC`, x, n)
}

#' C++ ile Hızlı Grup Ortalaması Hesaplama
#'
#' Bir vektörün değerlerini belirtilen gruplara göre gruplayarak
#' ortalamalarını hızlıca hesaplar.
#'
#' @param x Değerlerin bulunduğu sayısal vektör.
#' @param grup Grupları belirten karakter vektörü.
#' @return Grup isimlerini ve ortalamalarını içeren bir liste.
#' @export
grupOzetC <- function(x, grup) {
    .Call(`_ExamplePackage07_grupOzetC`, x, grup)
}

#' C++ ile Vektörün Karesini Alan Hızlı Fonksiyon
#' @param x Sayısal vektör
#' @export
vektorKareC <- function(x) {
    .Call(`_ExamplePackage07_vektorKareC`, x)
}

